local syntax = require "core.syntax"

syntax.add {
  files = "%.lit$",
  headers = "^#!.*[ /]lit",
  comment = "--",
  patterns = {
    { pattern = { '"', '"', '\\' },       type = "string"   },
    { pattern = { "%[%[", "%]%]" },       type = "string"   },
    { pattern = { "%-%-%[%[", "%]%]"},    type = "comment"  },
    { pattern = "%-%-.-\n",               type = "comment"  },
    { pattern = "-?0x%x+",                type = "number"   },
    { pattern = "-?%d+[%d%.eE]*",         type = "number"   },
    { pattern = "-?%.?%d+",               type = "number"   },
    { pattern = "%.%.%.?",                type = "operator" },
    { pattern = "[<>~=]=",                type = "operator" },
    { pattern = "[%+%-=/%*%^%%#<>]",      type = "operator" },
    { pattern = "[%a_][%w_]*%s*%f[(\"{]", type = "function" },
    { pattern = "[%a_][%w_]*",            type = "symbol"   },
  },
  symbols = {
    ["class"]       = "keyword2",
    ["else"]     = "keyword",
    ["false"]     = "keyword",
    ["for"]   = "keyword",
    ["function"]      = "keyword",
    ["if"]       = "keyword",
    ["null"] = "keyword",
    ["return"]   = "keyword",
    ["super"]    = "keyword",
    ["this"]    = "keyword",
    ["true"]      = "keyword",
    ["var"]    = "keyword",
    ["while"]   = "keyword",
    ["continue"]    = "keyword",
    ["break"]       = "keyword",
    ["new"]      = "keyword",
    ["export"]      = "keyword",
    ["is"]       = "keyword",
    ["static"]     = "keyword",
    ["operator"]     = "keyword2",
    ["get"]     = "keyword",
    ["set"]    = "keyword",
    ["in"]      = "keyword",
  },
}

