name: Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake . -DLIT_DEFINE_TEST=ON
    - name: make
      run: make
    - name: test
      run: python3 ./test.py
