name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: submodule init
      run: git submodule init
    - name: submodule update
      run: git submodule update
    - name: cmake
      run: cmake . -DDEFINE_TEST=ON
    - name: make
      run: make
    - name: test
      run: python ./test.py
